import { useState } from "react";
import type { T } from "../themes";
import { t } from "../i18n";
import { InfoSheet } from "./InfoSheet";
import licences from "../licences.json";

// Generated by scripts/licences.mjs from what actually ships. The notices
// themselves stay in English: they are legal text, and a translation of one
// is not the licence.
type Licence = { name: string; version: string; licence: string; text: string };

export function LicencesSheet({ onClose, T }: { onClose: () => void; T: T }) {
  const [open, setOpen] = useState<string | null>(null);
  const list = licences as Licence[];
  return (
    <InfoSheet title={t("Open source licences")} onClose={onClose} T={T}>
      <p style={{ color: T.textSub, fontSize: 13.5, lineHeight: 1.6, margin: "0 0 12px" }}>
        {t("MPTree is built on work other people share freely. These are their licences.")}
      </p>
      {list.map((l, i) => {
        const isOpen = open === l.name;
        return (
          <div key={l.name} style={{ borderBottom: i < list.length - 1 ? `1px solid ${T.border}` : "none" }}>
            <button
              onClick={() => setOpen(isOpen ? null : l.name)}
              aria-expanded={isOpen}
              style={{
                display: "flex", alignItems: "baseline", gap: 10, width: "100%", textAlign: "left",
                background: "transparent", border: "none", padding: "12px 2px", cursor: "pointer",
                color: T.text, fontFamily: "inherit",
              }}
            >
              <span style={{ flex: 1, fontSize: 14, fontWeight: 600, overflowWrap: "anywhere" }}>
                {l.name}{l.version ? <span style={{ color: T.muted, fontWeight: 400 }}> {l.version}</span> : null}
              </span>
              <span style={{ fontSize: 12, color: T.muted, flexShrink: 0 }}>{l.licence}</span>
            </button>
            {isOpen && (
              <pre style={{
                margin: "0 0 14px", padding: 12, borderRadius: 10, background: T.dim, color: T.textSub,
                fontSize: 11, lineHeight: 1.5, whiteSpace: "pre-wrap", overflowWrap: "anywhere",
                maxHeight: 280, overflowY: "auto", fontFamily: "ui-monospace, monospace",
              }}>
                {l.text || t("No licence file is included with this package.")}
              </pre>
            )}
          </div>
        );
      })}
    </InfoSheet>
  );
}
